<?php
//Custom Layouts
$layouts = array(
		'header_13' => array(
				'name' => 'ElectroServ Header Fullwidth Simple',
				'template' => '<p>[vc_row content_placement=\"middle\" hide_bg_image_on_tablet=\"\" hide_bg_image_on_mobile=\"\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1503849252701{padding-right: 3.8rem !important;padding-left: 3.8rem !important;}\"][vc_column column_align=\"left\" icons_position=\"left\" column_type=\"center\" offset=\"vc_col-md-2 vc_col-sm-offset-0\"][trx_sc_layouts_logo][/vc_column][vc_column fix_column=\"\" column_align=\"left\" icons_position=\"left\" offset=\"vc_col-md-7\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column column_align=\"right\" icons_position=\"left\" offset=\"vc_col-md-3 vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-untitled-1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" flip=\"\" text1=\"Call 24/7 for emergency service\" text2=\"800 132 4567\" link=\"tel:+8001324567\"][/vc_column][/vc_row][vc_row scheme=\"dark\" hide_bg_image_on_tablet=\"\" hide_bg_image_on_mobile=\"\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1503900985002{background-image: url(http://electroserv.ancorathemes.com/wp-content/uploads/2017/07/title_bg.jpg?id=348) !important;background-position: top left !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" css=\".vc_custom_1503901766860{margin-top: 1.45rem !important;}\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" title_align=\"default\" padding=\"none\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" use_featured_image=\"\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][vc_empty_space alter_height=\"medium\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" css=\".vc_custom_1503901800229{margin-top: 1.65rem !important;}\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1503849252701{padding-right: 3.8rem !important;padding-left: 3.8rem !important;}.vc_custom_1503900985002{background-image: url(http://electroserv.ancorathemes.com/wp-content/uploads/2017/07/title_bg.jpg?id=348) !important;background-position: top left !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1503901766860{margin-top: 1.45rem !important;}.vc_custom_1503901800229{margin-top: 1.65rem !important;}'
						)
				),
		'footer_298' => array(
				'name' => 'Footer',
				'template' => '[vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" css=\".vc_custom_1503906131203{margin-top: 1.6rem !important;}\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"\" logo=\"300\" description=\"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.\" logo_retina=\"555\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\"][vc_wp_text title=\"Address\"]<span class=\"trx_addons_footer_contacts\">8500&nbsp;Lorem Rd, Antelope, CA&nbsp;60606</span>[/vc_wp_text][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\" offset=\"vc_col-sm-offset-1\"][vc_wp_text title=\"Contacts\"]<span class=\"trx_addons_footer_contacts\"><a href=\"mailto:info@example.com\">info@example.com
</a><a href=\"tel:+8001324567\">(800) 132 4567</a></span>[/vc_wp_text][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\" offset=\"vc_col-sm-offset-1\"][trx_widget_socials title=\"Socials\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][vc_empty_space hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" css=\".vc_custom_1503907710096{margin-top: 0.3rem !important;}\"][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\"][vc_separator border_width=\"2\"][vc_wp_text]<a href=\"https://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\" rel=\"noopener\">AncoraThemes</a> &copy; {{Y}}. All rights reserved.[/vc_wp_text][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_layout_type' => 'footer',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"footer";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1503906131203{margin-top: 1.6rem !important;}.vc_custom_1503907710096{margin-top: 0.3rem !important;}'
						)
				),
		'header_493' => array(
				'name' => 'ElectroServ Header Fullwidth Simple Centered',
				'template' => '<p>[vc_row content_placement=\"middle\" hide_bg_image_on_tablet=\"\" hide_bg_image_on_mobile=\"\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1504283018547{padding-bottom: 1.95em !important;}\"][vc_column width=\"1/12\" icons_position=\"left\"][/vc_column][vc_column width=\"1/4\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_iconed_text icon=\"icon-untitled-15\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"1\" flip=\"1\" text1=\"Emergency Service Available\" text2=\"24/7\"][/vc_column][vc_column width=\"1/3\" fix_column=\"\" column_align=\"center\" icons_position=\"left\"][trx_sc_layouts_logo hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" logo=\"342\" logo_retina=\"554\"][/vc_column][vc_column width=\"1/4\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_iconed_text icon=\"icon-untitled-1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"1\" flip=\"\" text1=\"Call 24/7 for emergency service\" text2=\"800 132 4567\" link=\"tel:+8001324567\"][/vc_column][vc_column width=\"1/12\" icons_position=\"left\"][/vc_column][/vc_row][vc_row hide_bg_image_on_tablet=\"\" hide_bg_image_on_mobile=\"\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1504282986788{padding-top: 0.1rem !important;padding-bottom: 0.1rem !important;background-color: #f6f6f6 !important;}\"][vc_column width=\"1/12\" column_align=\"center\" icons_position=\"left\"][/vc_column][vc_column width=\"5/6\" column_align=\"center\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/12\" icons_position=\"left\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1504283018547{padding-bottom: 1.95em !important;}.vc_custom_1504282986788{padding-top: 0.1rem !important;padding-bottom: 0.1rem !important;background-color: #f6f6f6 !important;}'
						)
				),
		'header_496' => array(
				'name' => 'ElectroServ Header Simple',
				'template' => '<p>[vc_row content_placement=\"middle\" hide_bg_image_on_tablet=\"\" hide_bg_image_on_mobile=\"\" row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1504355706214{padding-right: 1.8rem !important;padding-left: 1.8rem !important;}\"][vc_column column_align=\"left\" icons_position=\"left\" column_type=\"center\" offset=\"vc_col-md-2\"][trx_sc_layouts_logo][/vc_column][vc_column fix_column=\"\" column_align=\"center\" icons_position=\"left\" offset=\"vc_col-md-8\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column column_align=\"right\" icons_position=\"left\" offset=\"vc_col-md-2 vc_hidden-sm vc_col-xs-12 vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-untitled-1\" hide_on_desktop=\"\" hide_on_notebook=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" flip=\"\" text2=\"800 132 4567\" link=\"tel:+8001324567\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_layout_type' => 'header',
						'trx_addons_options' => 'a:2:{s:11:"layout_type";s:6:"header";s:6:"margin";s:0:"";}',
						'panels_data' => 's:0:"";',
						'_wpb_shortcodes_custom_css' => '.vc_custom_1504355706214{padding-right: 1.8rem !important;padding-left: 1.8rem !important;}'
						)
				)
		);
?>